import random

"""
THIS FILE ONLY CONTAINS THE CONSTANTS THAT ARE GOING TO BE USED IN OUR PROGRAM.
THIS VARIABLES SHOULDN'T BE CHANGED, BUT THEY CAN BE CHANGED IN ORDER TO MODIFY
SOME ASPECTS OF THE PROGRAM

"""

WIDTH, HEIGHT = 256, 256    # GAME SIZE

BACKGROUND = 0              # BACKGROUND COLOR (not very useful, but it can be used 
                            # if you dont want a background wallpaper)
                            

TOTAL_PLATFORMS = 7         # NUMBER OF PLATFORMS. SHOULDN'T BE CHANGED IN THIS PROGRAM
                            # STATED BY THE PDF REQUIREMENTS

LEMMINGS_VELOCITY = 0.4     # VELOCITY OF LEMMINGS. CAN BE CHANGED

MAX_LEMMINGS= random.randint(10,20) # NUMBER OF LEMMINGS THAT WILL APPEAR. 
                                    # CAN BE CHANGED.

# NUMBER OF TOOLS THAT THE PLAYER WILL HAVE AVAILABLE.
# THESE CAN BE MODIFIED, BUT IT IS IMPORTANT TO TAKE INTO ACCOUNT THAT
# LEVELS ARE GENERATED RANDOMLY AND IMPOSSIBLE LEVELS CAN APPEAR.

MAX_LADDERS = random.randint(10,20)
MAX_UMBRELLAS = random.randint(5,10)
MAX_BLOCKERS = random.randint(5,10)
MAX_SHOVELS = random.randint(5,10)
